### ISSUE TITLE
Entities need filtering - nonsense returned on searches

### ISSUE THREAD

**Issue by ardunn** [materialsintelligence/matscholar-web#107]
On the search for application: light sensor, the last 3 results are
![image](https://user-images.githubusercontent.com/19936203/65732808-5d769900-e080-11e9-9853-859e9e93eee8.png)

@jdagdelen @AmalieT

**Comment by AmalieT** [comment]
I'm going to bandaid this by only displaying materials that parse through
the materials parser. Ultimately we should work on improving the accuracy
of the ner model imo.

**Comment by AmalieT** [comment]
Similar materials that only appear in a single DOI are now pushed through the materials parser. It seems to have removed most of these bad results.

**Comment by ardunn** [comment]
@AmalieT we still seem to have some leakage of the pesky "GmbH & co". E.g., on searching:"application: cathode" it says there are 126 relevant papers with GmbH & co as a material entity. There are also still some other entities which don't make sense to me, like "rGO" and "carbonaceous"

**Comment by ardunn** [comment]
Similarly, when searching for materials with phase: cubic heusler, 

![image](https://user-images.githubusercontent.com/19936203/65827066-4df37d80-e243-11e9-81ab-8a1f2dff630c.png)

The word "come" is registered as a material. The abstract is relevant (has to do with heuslers etc., which is good) but the entity which was extracted as a material was not an actual material

**Comment by lwestn** [comment]
"rGO" is "reduced graphene oxide" so that is correct, but "come" is obviously an error (from an NER perspective). There are actually only about 20 materials that are not normalized to a chemical formula, things like graphene, steel etc., so other than these everything that cannot be parsed to a chemical formula is either an NER error (e.g., "come") or a parsing error (e.g., "rGA" - this one probably happened because the r is lowercase, and so it wasn't flagged as an acronym during parsing). Maybe anything that is an NER/parsing error could just be removed from the mongo collection?? That would fix most of these errors.

**Comment by AmalieT** [comment]
@LeighWeston86  Did you ever happen to make a list of the non-formula materials?

**Comment by ardunn** [comment]
Similarly for "material: PbTe, application: thermoelectric":

The following entities are returned:
- global
- cooler
- nonequilibrium (this is a border case, but I'd more readily say this is a descriptor/phase?
- bi-doped (descriptor)
- feasible
- bottom-up
- non-toxic (descriptor)
- GmbH & Co.
- Asin (i might just be ignorant here, I've never heard of Asin material)

**Comment by lwestn** [comment]
Things like "bi-doped" or "nonequilbrium" might have been labelled as a descriptor in the training set; definitely "bi-doped" was labelled as a descriptor originally, I can't remember if we went back and changed it. "Asin" is not a material but "AsIn" is, so maybe the character part of the LSTM got confused (unless Asin was accidentally changed to AsIn during preprocessing?).

**Comment by lwestn** [comment]
https://github.com/materialsintelligence/matscholar-core/blob/master/matscholar_core/nlp/normalize.py

**Comment by ardunn** [comment]
Some more examples of this: "THE PHYSICAL SOCIETY" came up as an entity

**Comment by ardunn** [comment]
after testing these queries again, this is no longer an issue
