### ISSUE TITLE
Copyright information in abstract text

### ISSUE THREAD

**Issue by AmalieT** [materialsintelligence/matscholar-web#108]
10.1002/pssa.200925093;
10.1002/pssa.201127194;
10.1002/pssa.201300118;
10.1002/pssa.201300199;
10.1002/pssa.201300307;

All have "GmbH & Co" extracted as a material entity. This doesn't appear in the actual paragraph, just in the copyright information.

**Comment by jdagdelen** [comment]
I think we should cut all these out and put them in a "copyright" filed for each entry, then display it separately with each doc.

**Comment by ardunn** [comment]
related to #145

**Comment by ardunn** [comment]
contained by #145
