### ISSUE TITLE
Autocomplete should only suggest normalized entities

### ISSUE THREAD

**Issue by AmalieT** [materialsintelligence/matscholar-web#112]

**Comment by jdagdelen** [comment]
The way autocomplete works is it completes whatever you were typing but fills in the normalized version.

**Comment by AmalieT** [comment]
That doesn't seem to be what's happening on the front end right now? Try typing in Descriptor: Nanoparticle(s) for example.

**Comment by AmalieT** [comment]
Tagging this frontend since it seems that may be the issue here

**Comment by AmalieT** [comment]
@ardunn is this because of the way text is transferred from the entities boxes to the main search box?

**Comment by jdagdelen** [comment]
Maybe we switched this. However, shouldn't entity normalization happen on the back-end once a query comes in?

**Comment by AmalieT** [comment]
It does, but I thought from a user perspective it should be clear that searcing nanoparticle vs nanoparticles or SiO2 vs O2Si are equivalent. It helps highlight the added value that we have vs plain text search engines.

**Comment by ardunn** [comment]
The current frontend just uses ESAutosuggest like the old one did. I haven't goofed around with exactly what it is doing yet. I'll fix soon

**Comment by jdagdelen** [comment]
The ESAutosuggest has two fields available in its results list, 'original' and 'normalized'. Right now as we have it defined we're using the default filed of 'original'. 

https://github.com/materialsintelligence/matscholar-web/blob/1eb2ecb9cd8ea7bb77b70f8bb31657eeeeb498a1/matscholar_web/search/view.py

**Comment by jdagdelen** [comment]
Ok, I just switched it to display and fill normalized entities on the staging site. Let's try it out and see how we feel about that.

**Comment by AmalieT** [comment]
Feels ok, but I wonder if there's an intuitive way to have the normalization happen between transferring from the entity box to the main search box?

**Comment by jdagdelen** [comment]
There is a way to do that. Just have to modify how ESAutosuggest works on the React side.
However, this might be confusing to the user. I think the best solution is to normalize on the backend and indicate to the user that it’s also searching on equivalent terms.
On Tue, Oct 1, 2019 at 1:45 PM, AmalieT <notifications@github.com> wrote:
Feels ok, but I wonder if there's an intuitive way to have the normalization happen between transferring from the entity box to the main search box?

**Comment by AmalieT** [comment]
Let's revert the normalization change on ESAutoSuggest then?

**Comment by computron** [comment]
I think this is superceded by #124 - reopen if needed
