### ISSUE TITLE
Autocomplete has many duplicate suggestions

### ISSUE THREAD

**Issue by AmalieT** [materialsintelligence/matscholar-web#114]
6 of the top 10 suggestions for "x-ray di" are "x-ray diffraction"

**Comment by AmalieT** [comment]
@jdagdelen I'm think we re-index the autocomplete from the "_ids" field of entities_dois? I'm going to have some cleanup of material names happen there too

**Comment by jdagdelen** [comment]
This is a result of the normalization. The original phrases being matched are different but they’re not being displayed. I’m not sure how we would fix that issue without some detailed work inside of the ES Autosuggest component.

On Tue, Oct 1, 2019 at 1:46 PM, AmalieT <notifications@github.com> wrote:
6 of the top 10 suggestions for "x-ray di" are "x-ray diffraction"

**Comment by AmalieT** [comment]
ahhh that makes sense. I guess the ultimate fix here is related to what we end up doing with #112 then.

**Comment by jdagdelen** [comment]
This was just a test.
