### ISSUE TITLE
Some entities queries still slow on the front end

### ISSUE THREAD

**Issue by AmalieT** [materialsintelligence/matscholar-web#116]
Searching for Material: "graphite" on entities search takes ~7seconds. The backend takes 2 seconds for that search.

I'd suggest changing the query on entities searches to use top_k=10, so only the 10 most common results of each entity type are returned. This would hugely reduce the size of the result object and the formatting time.
It would come at the cost of not knowing how many total results of each type there were, but if people feel like that's a good feature to have (I don't tbh), we can change what the backend returns to accomodate this.

**Comment by ardunn** [comment]
I don't think this is an issue any longer since `top_k` is set in all rester calls now
