### ISSUE TITLE
add example queries

### ISSUE THREAD

**Issue by computron** [materialsintelligence/matscholar-web#120]
add example queries, above the main search bar, in smaller gray text

Ideally we should rotate among ~20 or so examples that show off the various types of searches

**Comment by ardunn** [comment]
@AmalieT @jdagdelen @computron use this issue as a collection of cool example searches you think of (or would like to see on the frontend), I'll add them to the examples when I add the code


```
application: spintronics, property: doped
```

**Comment by ardunn** [comment]
This has been implemented as rotating example searches as the placeholder for the search bar and also a dedicated example search button
