### ISSUE TITLE
Logo looks like a microchip

### ISSUE THREAD

**Issue by computron** [materialsintelligence/matscholar-web#122]
I think the logo is rendered in good quality, but it looks like a microchip

**Comment by computron** [comment]
https://images.app.goo.gl/ZaeQWeBLMtKA9ZWA9

**Comment by ardunn** [comment]
lol

ok will change to something else

**Comment by ardunn** [comment]
@computron fixed? its just a bunch of rectangles now

unless you want to make a old-timey renaissance one, or we can revert to the old one if @jdagdelen   wants to change the color scheme a bit

**Comment by computron** [comment]
Could you do something like this? but flipped across the vertical axis?

https://www.google.com/imgres?imgurl=http%3A%2F%2Fwww.clker.com%2Fcliparts%2Fi%2Fd%2F3%2FV%2Fu%2F9%2Fstack-of-papers-blue.svg.med.png&imgrefurl=http%3A%2F%2Fwww.clker.com%2Fclipart-stack-of-papers-blue.html&docid=GuJraKY401EF4M&tbnid=75eqvXNzQsh1kM%3A&vet=10ahUKEwjJtrvJo6blAhUmHzQIHYDvCqAQMwhqKAgwCA..i&w=299&h=246&bih=1207&biw=1370&q=stack%20of%20papers%20clipart&ved=0ahUKEwjJtrvJo6blAhUmHzQIHYDvCqAQMwhqKAgwCA&iact=mrc&uact=8

**Comment by computron** [comment]
If you add the horizontal lines indicating text on the top page, I'd make those horizontal lines look like a journal article. E.g., a title horizontal line, a block of horizontal lines at top corresponding to abstract (single column), and maybe two columns of text past that. Then it will look like a journal article

**Comment by ardunn** [comment]
Sure, sounds good

also just pasting this here so ur example is in this thread
![image](https://user-images.githubusercontent.com/19936203/67122143-00af5f80-f1a2-11e9-9461-284c2c4d33dd.png)
