### ISSUE TITLE
users should get actual paper count AND filterable list of journals

### ISSUE THREAD

**Issue by computron** [materialsintelligence/matscholar-web#123]
* The 5,000,000 abstracts on the front page should be updated to a live count of the number of abstracts
* The "5,000,000" abstracts should be a clickable link that brings you to a page (or the About Page) that lists all the journals that are currently being parsed. Since this is a long list, you might want to use some kind of frontend component that allows you to start typing and just autocompletes the results. e.g. I can start typing "Physical Review ..." and then it will start suggesting "Physical Review B", "Physical Review Letters", etc if those journals are present in the database.

**Comment by ardunn** [comment]
done.
