### ISSUE TITLE
React autosuggest doesn't highlight/select on keypresses

### ISSUE THREAD

**Issue by ardunn** [materialsintelligence/matscholar-web#126]
Autosuggest should be able to use arrow keys and "Enter" to select the term you want to autocomplete. Also should highlight the selection you are currently on, whether using keys or mouse.

**Comment by jdagdelen** [comment]
I'm not sure this is something we can fix quickly.

**Comment by ardunn** [comment]
generally, what do we need to do to fix? just edit the react component?

**Comment by jdagdelen** [comment]
fixed in dash_elasticsearch_autosuggest==1.0.0
