### ISSUE TITLE
what keywords are available for searching?

### ISSUE THREAD

**Issue by computron** [materialsintelligence/matscholar-web#137]
It's unclear what keywords are available for search. Maybe a button with instructions on available keywords would help.

Are there any "secret" (non entity-type) keywords already available like "anonymous_formula: ABC3"? If so I'd like to use them for some of the example searches

**Comment by ardunn** [comment]
now taken care of with a tooltip when you mouse over the search box or label

<img width="835" alt="image" src="https://user-images.githubusercontent.com/19936203/67055327-8d9fdd80-f0fc-11e9-9b26-ed7cc55a18ec.png">
