### ISSUE TITLE
count of abstracts search shown to users (e.g. 4.9M abstracts) should reflect only relevant abstracts

### ISSUE THREAD

**Issue by computron** [materialsintelligence/matscholar-web#138]
since that is what is being searched on

**Comment by ardunn** [comment]
this is exclusively a backend issue. `rester.get_db_stats` needs to return the correct info.

**Comment by ardunn** [comment]
@jdagdelen

**Comment by AmalieT** [comment]
My reasoning was that the wording is "To date, our database contains x analyzed abstracts", and we have analyzed the not-relevant abstracts, and found them not relevant

**Comment by AmalieT** [comment]
But I've changed it to be relevant only anyway

**Comment by ardunn** [comment]
thanks @AmalieT !
