### ISSUE TITLE
matscholar needs a "Contact" button at the footer of the page

### ISSUE THREAD

**Issue by computron** [materialsintelligence/matscholar-web#148]
Steps to achieve:

# Route A (preferred)
1. Create a Discourse group for MaterialsIntelligence (ask Alex Ganose if you need help setting this up; it should be straightforward)
2. Have the footer be a link to that Discourse group

# Route B (not preferred)
1. Create a mailing list for matscholar (put entire team on it) - e.g. via LBL lists
2. Have the footer just be a mailto that mailing list

# Route C (not preferred)
1. Have the footer link to the matscholar-web issues page on Github - just say "Report an Issue" and link to the issue tracker

**Comment by ardunn** [comment]
Ok I requested an open-source (free) discourse account for MaterialsIntelligence. Once that's set up I'll add a link to it.

For the location of the link, what do people think about putting it in the nav bar instead (near where the Github link is now, or replacing it)? I feel like there is more visibility there

**Comment by ardunn** [comment]
This is done 90793ecafa0b896d7d1f87e1fc93da675cf19ac6
