### ISSUE TITLE
a few more guided search "example text" to add to the list

### ISSUE THREAD

**Issue by computron** [materialsintelligence/matscholar-web#150]
Feel free to filter out any of these suggestions that are very similar to existing Example searches:

application: thermoelectric
application: battery, phase: spinel
characterization: scanning electron microscopy, phase: perovskite

I didn't get to test the last query, things kind of broke down on the site (or the site was being updated). So maybe make some kind of modification on that query if it's not giving back good results

**Comment by ardunn** [comment]
I tested the last one, results make sense for the most part. Lots of results returned. 

One thing worth noting is that `scanning electron microscopy` had a score of 0.96, not 1.0, which is something to look into.


@computron idk if site was being updated (frontend at least), what did it do (so we can fix it)?
