### ISSUE TITLE
Search logic is unclear

### ISSUE THREAD

**Issue by ardunn** [materialsintelligence/matscholar-web#151]
If I type in 

```material: PbTe, SnSe  application: thermoelectric```

Passed to the rester, this is:

```
entities = {"material": ["PbTe", "SnSe"], "application": ["thermoelectric"]} # correct me if this is wrong
```

The logic I would expect is:

"(PbTe OR SnSe) AND thermoelectric"

E.g., if we had 1k results for "PbTe AND thermoelectric" and 2k results for "SnSe and thermoelectric", "(PbTe OR SnSe) AND thermoelectric" would return 3k results?

What the search *seems* like it is returning is:

"(PbTE AND SnSe) AND thermoelectric"

Which gives a lot less results than you'd expect.

@AmalieT @jdagdelen

**Comment by jdagdelen** [comment]
I also think it should be OR within entity classes.

**Comment by computron** [comment]
I agree that absent any more specific guidance from the user, it would be better to OR within entities but AND across entities as the default behavior

**Comment by AmalieT** [comment]
Searches are now OR within entity types but AND across types
