### ISSUE TITLE
Add Journal Suggestion App

### ISSUE THREAD

**Issue by ardunn** [materialsintelligence/matscholar-web#153]
The backend for this is already working, but needs to be updated in the rester

Once it is updated in the rester it can be added to the frontend.

**Comment by jdagdelen** [comment]
I was just playing around with this and it seems like the Journal of Electroceramics is suggested for a ton of abstracts in our example set. @kevinyang8 It seems like there may be some biasing effects that we should work on. I don't this this disqualifies the app, but we should put a disclaimer on it and describe how the suggestions are calculated.

**Comment by ardunn** [comment]
oops, this issue should be closed. we can add more specific ones for problems in the app
