### ISSUE TITLE
journal predictor integrated into "extract entities" app

### ISSUE THREAD

**Issue by computron** [materialsintelligence/matscholar-web#163]
The extract entities app should have a second button called "Suggest journals".

Clicking it should call the already existing backend Rester function to get a list of suggested journals based on the abstract text (ask @jdagdelen or @kevinyang8 for the function name).

Then all you need to do is format that into a table as output. This should be pretty simple given the existing backend function, let me know if it sounds complicated

**Comment by jdagdelen** [comment]
Rester.get_journal_suggestion(abstract)

**Comment by ardunn** [comment]
this is now live on staging
