### ISSUE TITLE
Two minor "analyze abstract" issues

### ISSUE THREAD

**Issue by computron** [materialsintelligence/matscholar-web#166]
1. "Enter a scientific abstract's text for named entity extraction" should be renamed to "Enter a scientific abstract's text for analysis" - since we now do other types of analysis (e.g., journal prediction)

2. If you click "Extract entities" and no entities are detected, it should explicitly write that no entities were detected. Currently it seems to do nothing. And if you click "suggest journals" then click "extract entities", the journal list doesn't even disappear. See example abstract below:

```
When metallic glasses are subjected to mechanical loads, the plastic response of atoms is heterogeneous. However, the degree to which the plastic units are correlated with the structural defects frozen in the quenched glass structure is still elusive. Here, we introduce a machine learning framework to predict the plastic heterogeneity of atoms in Cu-Zr metallic glasses solely from the undeformed, quenched configuration. We propose that an atomic-scale quantity, “quench-in softness”, calibrated from a gradient boosted decision tree model trained on a set of short- and medium-range site features, can identify plastically susceptible sites at various strain levels with high accuracy. The predictive ability is further confirmed in that a model trained on a single composition and quench rate retains high accuracy on other compositions and quench rates without any further training. We also quantitatively assess historical site descriptors against our method, demonstrating that the regularity-related features introduced in this work are more predictive and may play an important role in future glass characterization. Our work presents a general, data-centric framework that could potentially be used to address the structural origin of any site-specific property in metallic glasses.
```

**Comment by ardunn** [comment]
Wow that abstract is a really strange case. I'll have to investigate it some more. Its not even warning that it's "not relevant", so this is a case where an abstract is **both** relevant and yet has no entities? I mean how is "glass" not an entity? Or "strain"?  How can it be predicting there are **no** entities? @jdagdelen

**Comment by ardunn** [comment]
Ok on closer inspection this is not because no entities were detected. The backend is returning an internal user tag not supposed to be in the response which is crashing the frontend. There are indeed entities detected, and the relevance classifier is working.

**Comment by ardunn** [comment]
in the meantime I've updated the frontend to ignore the I-* tags. These issues are closed
