### ISSUE TITLE
MRS Symposium Search

### ISSUE THREAD

**Issue by jdagdelen** [materialsintelligence/matscholar-web#167]
Here’s a view plan I drew in the hackathon. There is a new branch of this repo specifically for the MRS site called “mrs”.

![7AB57CDF-71AE-4B6E-B8F8-5F02CBBD7134](https://user-images.githubusercontent.com/9101793/68890019-f023d380-06d2-11ea-9d02-888c34107215.jpeg)

**Comment by ardunn** [comment]
no longer needed, all new issues are on matscholar-mrs
