### ISSUE TITLE
search doesn't seem to be much different than what a full text search would give

### ISSUE THREAD

**Issue by computron** [materialsintelligence/matscholar-web#170]
If I search "high - throughput calculations", I just get a bunch of random high-throughput stuff (experiment or calculations). Sometimes this flexibility is good (e.g., "high-throughput first-principles"), sometimes it is not ("large - area high - throughput deposition", which is NOT what I asked for).

Essentially, I am having trouble seeing the point of extracting entities at all. All these tags get extracted from the abstract, but I can't do anything with those tags ...

**Comment by computron** [comment]
As another example, I did a search for "pocket multiplicity" which was a detected entity in one of my abstracts on thermoelectrics [[EN14.08.03]]

I wasn't expecting to see much, which would have been fine. But instead I got a bunch of completley non-relevant things that were just a waste of time to browse through.

**Comment by computron** [comment]
Note that I get *better* results (just 1 false hit) on the above query from the default MRS search site:

https://mrsfall2019.zerista.com

So the results need to be better than that in order for this to really be useful

**Comment by ardunn** [comment]
moved to matscholar-mrs
