### ISSUE TITLE
User interface / experience for "suggest similar" should be improved

### ISSUE THREAD

**Issue by computron** [materialsintelligence/matscholar-web#171]
For the "suggest similar" feature:

- the button should be bigger / more prominent
- the similar abstracts should appear in a new page instead of being grouped underneath in the search result. For example, the search bar should allow the syntax: "similar: BI01.01.01" which would be the same as doing a search on similar abstracts. Note that IMO it just gets too messy to cram a bunch of similar abstracts as an indent to the main search result.
- there needs to be a way to read the abstracts of the similar abstracts - not just the titles / authors. if the bullet above is implemented (similar abstracts is like doing a search) it should just work out of the box

**Comment by computron** [comment]
Also whenever I click "suggest similar" for two abstracts in the same search result - I get confused of where to find the result ... e.g. forgetting to tediously scroll down to get the result for the second abstract

**Comment by ardunn** [comment]
moved to matscholar-mrs repo
