### ISSUE TITLE
suggest similar is "stucK"

### ISSUE THREAD

**Issue by computron** [materialsintelligence/matscholar-web#172]
- Type "kedar hippalgoankar" into the search
- clikc "suggest similar" for the first hit: New Horizons in Thermoelectric Materials—Inorganic-Organic Hybrids and Machine Learning for Inorganic Crystals

For me it is stuck ...

**Comment by ardunn** [comment]
probably crashed the app lol

**Comment by ardunn** [comment]
also @computron I'm gonna repost these issues to the actual repo which is housing the mrs code, 

https://github.com/materialsintelligence/matscholar-mrs/issues

**Comment by ardunn** [comment]
moved to matscholar-mrs
