### ISSUE TITLE
No entities extracted

### ISSUE THREAD

**Issue by computron** [materialsintelligence/matscholar-web#173]
No entities extracted for:
Accelerated Materials Discovery Using Theory, Computation, Optimization and Natural Language Processing
MT03.04.01 - 08:00 AM, Tuesday Dec 03, Hynes, Level 2, Room 208
Anubhav Jain
Lawrence Berkeley National Laboratory

You should do a unit test to check for abstracts with no entities extracted to make sure this doesn't happen

**Comment by ardunn** [comment]
moved to matscholar-mrs
