### ISSUE TITLE
suggest similar - underlying algorithm not that great

### ISSUE THREAD

**Issue by computron** [materialsintelligence/matscholar-web#174]
This was discussed a little bit in the Slack, but I find the suggest similar feature to give only mediocre results.

Take the paper:
Ultrahigh Intrinsic Thermoelectric Performance, Phase Stability and Defect Energetics of Full-Heusler Compounds
EN14.08.03

The results are
- Non-Radiative Recombination in Metal Halide Perovskites—Thin Films vs Bulk Crystals [[poor]]
- Quantification of Uncertainity in the Lattice Thermal Conductivity of Thermoelectric Materials from a First-Principles Prediction Method [[OK]]
- Revealing the Intrinsic Electronic Structure of ZrNiSn Half-Heusler Thermoelectric Materials [[good]]
- Identification and Comparison of Interstitial Defect Configurations in Alumina [[poor]]

**Comment by computron** [comment]
As another example, for this abstract:

MT03.01.07 - Robot-Accelerated Perovskite Investigation and Discovery (RAPID)—A High-throughput Approach Towards Metal Halide Perovskite Single Crystal Discovery

One of the top similar hits is:
Exploring Catalyst Chemistries beyond Scaling Laws using Statistical Learning

which is not nearly as simialr as other abstracts on either robotic synthesis or perovskite materials

**Comment by ardunn** [comment]
moved to matscholar-mrs
