### ISSUE TITLE
Matscholar-MRS - overall

### ISSUE THREAD

**Issue by computron** [materialsintelligence/matscholar-web#176]
Overall, I think the amount of progress on the MRS web site is great!

But, it's still not at the point where we should release it. The criteria for release is that everyone should feel amazed when using it and want to tell all their friends about it. I would encourage you to find some people in your research groups going to MRS and beta test it with them. If they are blown away you are on the right track. Otherwise, you need to keep hacking ...

**Comment by ardunn** [comment]
moved to matscholar-mrs repo
