### ISSUE TITLE
Dropdown for "query n documents" or search span

### ISSUE THREAD

**Issue by ardunn** [materialsintelligence/matscholar-web#189]
IIRC, backend currently queries N (=10K?) documents  for each search, picked at random or something. We could make this a user parameter with the proviso a warning is shown "More comprehensive searches require more time to run". I see a possible problem with the website is that people might have a very niche search and their search is not within the N docs searched, resulting in none/few results. 

@jdagdelen @AmalieT might be able to comment more on whether this is feasible/recommended

**Comment by AmalieT** [comment]
Hey Alex,

We do it a little more intelligently than that - we don't query 10k random
documents, we query 10k matching documents. Fetching a list of all matching
dois is quick with our current set-up, it's making the pivot tables (ie
summaries) that's slow. We could make this a front end option, I'm worried
the behavior is pretty opaque though.

**Comment by ardunn** [comment]
Ah gotcha, yes I mean matching documents sorted at random; ie, not ranked by any metric other than there is at least one matching term among possibly many?

**Comment by AmalieT** [comment]
Matches of different entity types ar AND searches if that's what you mean?

**Comment by ardunn** [comment]
Also, from a user perspective, will people care whether search is opaque or
not? I think they’ll care more about whether they get results back

**Comment by AmalieT** [comment]
That option specifically sounds opaque? It will basically never change much
unless it's set to <1k.

**Comment by ardunn** [comment]
Ok I'll take your word on that :)
