### ISSUE TITLE
"NSW" materials search

### ISSUE THREAD

**Issue by computron** [materialsintelligence/matscholar-web#43]
When I search for the application "light sensor" in the summary app, one of the top materials is "NSW".

Curious what NSW was, I did a search for NSW in the search app. But nothing showed up... curiously, NSW does show up in the summary app as a material

Is this a normalization issue? Something else?

**Comment by computron** [comment]
I think I (partially) figured it out

WSN is an acronym for "Wireless Sensor Network"

The entity parsing thinks it's a chemical formula and normalizes to NSW

Also, I should clarify that nothing shows up in the search app for material=NSW + application=light sensor. Just material=NSW does give some results

**Comment by jdagdelen** [comment]
Olga’s newest parser may be able to figure this out.

**Comment by lwestn** [comment]
That looks for sure like an NER error. The classifier is the most accurate for materials, but when it fails it's usually on an acronym, especially when all of the letters are chemical elements.

I am not sure why the results don't show up in the search app but I'll check it out.

**Comment by ardunn** [comment]
No longer an issue as of 11ab5d998a1477d2765e124dc13f6b5983b17e2c
