### ISSUE TITLE
Replace "clickable dois" with "download list of dois"

### ISSUE THREAD

**Issue by jdagdelen** [materialsintelligence/matscholar-web#53]
@LeighWeston86 Do you have time for this?

**Comment by lwestn** [comment]
Do you mean remove clickable links entirely? Isn't this useful for people to browse? The dois can already be downloaded as csv.

**Comment by jdagdelen** [comment]
I think it won't get used much compared to being able to download a list of links. Unless we have the option to "show table of papers" or the link takes them to the search page for those papers.

**Comment by lwestn** [comment]
OK. I think this was a feature request from @computron so I'll check with him before removing the links.

**Comment by computron** [comment]
I wanted to click to see a *separate page* with all the paper titles / dois, which you could click to go directly to the relevant article

It is nice when there is a result to be able to quickly dig into the articles that support that result. I would not simply do a download-only

**Comment by computron** [comment]
(I also mentioned that if a separate page was difficult in Dash, then a modal dialog with scrollbar would be fine)

**Comment by jdagdelen** [comment]
Ok, we can do a separate page with the titles and DOIs. I think that would be useful.
