### ISSUE TITLE
summary for descriptor="glass" just seems to hang

### ISSUE THREAD

**Issue by computron** [materialsintelligence/matscholar-web#56]

**Comment by jdagdelen** [comment]
Summaries for entities with lots of papers are very resource intensive. This causes them to hang.

**Comment by computron** [comment]
Can these summaries be built in advance rather than on the fly?

**Comment by jdagdelen** [comment]
Yeah, we can do it for the most common ones and we’re also going to add caching.

On Mon, Aug 5, 2019 at 9:21 AM, Anubhav Jain <notifications@github.com> wrote:
Can these summaries be built in advance rather than on the fly?

**Comment by ardunn** [comment]
For the queries material: glass and descriptor: glass, the search either hangs or gets no results.

**Comment by ardunn** [comment]
fixed as of commits leading up to 839a6d1e8f7794acc3e9eb9be9abe5defffd371f
