### ISSUE TITLE
explanation of syntax for anonymous formula

### ISSUE THREAD

**Issue by computron** [materialsintelligence/matscholar-web#79]
Note that there are multiple possible syntaxes for anonymous formula, and it will not be clear to a new user (who may have not heard the term before) what the syntax should look like.

Ideally there can be some kind of information box telling you what is in-bounds for an anonymous formula search.

Similar for elements search, although that one is a bit more intuitive (still, it would be nice to explain that it's comma separated with a negative for exclude)

**Comment by ardunn** [comment]
superceded by #93
