### ISSUE TITLE
Use DCC store to store search results

### ISSUE THREAD

**Issue by AmalieT** [materialsintelligence/matscholar-web#89]

**Comment by ardunn** [comment]
Search results session cached in memory already with memoize for queries within the timeout period.

Session storage seems like the main use case for this. Local storage, especially during this development period, seems like it would be bad. E.g., 

(a) user gets some results with problems in it, 
(b) bad results get cached in local storage 
(c) we update the backend to give better results 
(d) user comes back a month later, repeats search, and gets the same results bc. they're cached

We could of course check dates/versions/hashes or something, at the risk of making things even more unmaintainable and complicated. Idk

**Comment by ardunn** [comment]
@AmalieT think this is a good idea? If so, I'll work on implementing. But from my perspective it seems like it would solve a non-problem and just complicate things more. This seems like something we could implement in the future _if_ we are getting usage problems on server side from lots of users.

**Comment by AmalieT** [comment]
Yeah, I agree. After all the work we put into speeding up search queries,
it seems unnecessary.

**Comment by ardunn** [comment]
Cool, closed.
