### ISSUE TITLE
Fix colors and formatting

### ISSUE THREAD

**Issue by ardunn** [materialsintelligence/matscholar-web#98]
The colors are terrible, use a better colorscheme beyond the pre-made colorschemes in bulma

**Comment by AmalieT** [comment]
More elements could use colour in general too

**Comment by ardunn** [comment]
Also: consider moving navigation buttons to top navbar (integrated with logo) similar to https://github.com/stevej2608/dash-spa/blob/master/docs/img/signin.png

**Comment by ardunn** [comment]
@jdagdelen needs journals and authors as green

**Comment by ardunn** [comment]
property value and property colors are too close together, need to use different colors

**Comment by ardunn** [comment]
entity highlighting should not be buttons (on both extract app and search), should be underlined text or similar
